Round numbers for Incito
shopgun/shopgun-js-sdk pull request #167
Opened 2023-02-16 14:20 UTC by mortenbo

2023-02-16 14:27 UTC, klarstrup requested changes
Me no comprendo, decimal pixel values are valid 🤔

2023-02-16 14:31 UTC, klarstrup commented
If this somehow addresses a11y support issues we were talking about: Can we just do this on the incito generation side for problematic incitos instead? Then they retain control and the fix is out instantly rather than needing to propagate through the SDK

2023-02-16 14:33 UTC, mortenbo commented
@klarstrup OK, reverted it now. They'll fix on Incito. But we would still like to clean the style.

2023-02-16 14:43 UTC, klarstrup approved these changes
Nits

2023-02-16 14:43 UTC, klarstrup commented on lib/incito-browser/incito.ts
> +                        if (key && key.length && value && value.length) {
Don't need this length check, empty strings are falsey by themselves

2023-02-16 14:43 UTC, klarstrup commented on lib/incito-browser/incito.ts
> +                            styles[key] = value.trim();
`value` could be an empty string after the `trim()`, consider trimming before the above `if `clause

2023-02-16 15:04 UTC, mortenbo commented on lib/incito-browser/incito.ts
> +                            styles[key] = value.trim();
True - better now?

2023-02-16 23:20 UTC, klarstrup approved these changes

2023-02-17 07:41 UTC, mortenbo commented
@martensievers Shall we still go with this in the SDK or will you fix it server-side?

2023-02-28 13:19 UTC, closed without merging