conditional controls when not lazy
shopgun/shopgun-js-sdk pull request #268
Opened 2024-12-05 16:57 UTC by t-lansing

2024-12-05 23:08 UTC, klarstrup requested changes

2024-12-05 23:08 UTC, klarstrup commented on lib/incito-browser/incito.ts
> +                }
just move this out of the if statement entirely instead of duplicating it

2024-12-06 09:40 UTC, t-lansing commented
@klarstrup I will keep an eye out on clients that don't lazyload and their video settings, so that their videos don't autoplay.

2024-12-06 10:21 UTC, t-lansing commented
@jrlarano can you test this befrie deploy?

2024-12-06 10:38 UTC, jrlarano commented
Done testing it and it works as expected 🚀

2024-12-06 10:38 UTC, merged